---

- name: Install Dependencies
  block:

# Docker and friends
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install docker and its dependecies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: Jinja2 template for docker-daemon
      template:
        src:   ../template/daemon.json.j2
        dest:  /etc/docker/daemon.json
        owner: root
        group: root

# KVM hypervisor and friends
    - name: Install KVM/Qemu and Libvirt
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: True
      vars:
        packages:
        - qemu-kvm 
        - libvirt-daemon 
        - bridge-utils 
        - virtinst 
        - libvirt-daemon-system 
        - virt-top 
        - libguestfs-tools 
        - libosinfo-bin  
        - qemu-system 
        - virt-manager
        - genisoimage

    - name: Jinja2 template for libvirt-daemon
      template:
        src:   ../template/qemu.conf.j2
        dest:  /etc/libvirt/qemu.conf
        owner: root
        group: root 

# Terraform
    - name: Install Terraform, snap --classic
      snap:
        name: "{{ packages }}"
        classic: yes
      vars:
        packages:
        - terraform

  become: True
  become_user: root
