---

- name: Install dependencies
  block:

# Restart services
    - name: Restart docker
      service:
        name: docker
        state: restarted

    - name: Restart libvirtd
      service:
        name: libvirtd  
        state: restarted

  become: True
  become_user: root