---

- name: Provisioning Ubunt for kvm host
  hosts: local
  connection: local
  gather_facts: True
  ignore_errors: True

  roles:
    - base_env/roles/installDep
    - base_env/roles/restartServices